include: package:flutter_lints/flutter.yaml

linter:
  rules:
    use_null_aware_elements: false

    curly_braces_in_flow_control_structures: false
    unintended_html_in_doc_comment: false

    deprecated_member_use: false
